### PR TITLE
Start up files

### PR DESCRIPTION
**Pull request by profxj**
Getting the repo started

### CODE REVIEW

**Comment by ntejos** [comment]
Looks good.

**Comment by profxj** [comment]
This goes faster if you merge

**Comment by profxj** [comment]
I'll comment not to if I'm still working on something.  Thanks

**Comment by ntejos** [comment]
For some reason, I cannot merge. Did you give me write permissions?

**Comment by profxj** [comment]
It must be that I added you to the Organization but not the Repo.

Just invited you.

**Comment by ntejos** [comment]
Indeed.

**Pull request merged**
